# Generated by Django 4.2 on 2023-06-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfaApp', '0006_regiuser_delete_reguser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_1', models.IntegerField()),
                ('channel_2', models.IntegerField()),
                ('channel_3', models.IntegerField()),
                ('channel_4', models.IntegerField()),
                ('channel_5', models.IntegerField()),
                ('channel_6', models.IntegerField()),
            ],
        ),
    ]
